### ISSUE TITLE
Missing scipy dependency

### ISSUE THREAD

**Issue by karel-brinda** [karel-brinda/prophyle#181]
```
(z) sph188-115:p karel$ prophyle_merge_trees.py /Users/karel/prophyle/test_bacteria.nw test_idx/tree.nw
Traceback (most recent call last):
  File "/Users/karel/miniconda/envs/z/lib/python3.5/site-packages/ete3/clustering/clustvalidation.py", line 196, in <module>
    from scipy import stats
ImportError: No module named 'scipy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/karel/miniconda/envs/z/bin/prophyle_merge_trees.py", line 11, in <module>
    load_entry_point('prophyle==0.1.0.31', 'console_scripts', 'prophyle_merge_trees.py')()
  File "/Users/karel/miniconda/envs/z/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/Users/karel/miniconda/envs/z/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/Users/karel/miniconda/envs/z/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2258, in load
  File "/Users/karel/miniconda/envs/z/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/Users/karel/miniconda/envs/z/lib/python3.5/site-packages/prophyle/prophyle_merge_trees.py", line 13, in <module>
    from ete3 import Tree
  File "/Users/karel/miniconda/envs/z/lib/python3.5/site-packages/ete3/__init__.py", line 61, in <module>
    from .clustering.clustertree import *
  File "/Users/karel/miniconda/envs/z/lib/python3.5/site-packages/ete3/clustering/__init__.py", line 40, in <module>
    from .clustertree import *
  File "/Users/karel/miniconda/envs/z/lib/python3.5/site-packages/ete3/clustering/clustertree.py", line 43, in <module>
    from . import clustvalidation
  File "/Users/karel/miniconda/envs/z/lib/python3.5/site-packages/ete3/clustering/clustvalidation.py", line 199, in <module>
    from . import stats
  File "/Users/karel/miniconda/envs/z/lib/python3.5/site-packages/ete3/clustering/stats.py", line 1933, in <module>
    geometricmean = Dispatch ( (lgeometricmean, (ListType, TupleType)), )
NameError: name 'ListType' is not defined
```

**Comment by karel-brinda** [comment]
It seems that it is a bug of ETE3:
https://github.com/etetoolkit/ete/issues/253

**Comment by karel-brinda** [comment]
@simonepignotti @salikhov-kamil I have not observed this bug since its reporting. Have you seen it since then? If not, I suggest that we close this issue and reopen only if it reappears.

**Comment by simonepignotti** [comment]
@karel-brinda today I tried installing ProPhyle from scratch with Kamil and we did not observed it. I guess the ete3 installation script has been corrected since then, so I agree with closing this issue.

**Comment by karel-brinda** [comment]
Observed also by @junaruga. Happens during ProPhyle installation via PyPI.
