### ISSUE TITLE
Exceeding memory while assembling

### ISSUE THREAD

**Issue by simonepignotti** [karel-brinda/prophyle#189]
Launching `prophyle index bacteria.nw bacteria_idx` with 8 threads (but also 4, only works with 2) on a machine with 16GB of RAM (Karel's office) exceeds memory while assembling. The problem is node `n1493` (Escherichia Coli), which has 91 fasta files associated to its leaves.
```
...
starting propagation for n1033.full.fa
/home/simone/prophyle/lib/python3.5/site-packages/prophyle/prophyle_assembler/prophyle_assembler -S -k 31 -i ./n1014.full.fa -i ./n1015.full.fa -i ./n1016.full.fa -i ./n1017.fu
ll.fa -i ./n1018.full.fa -i ./n1019.full.fa -i ./n1020.full.fa -i ./n1021.full.fa -i ./n1022.full.fa -i ./n1023.full.fa -i ./n1026.full.fa -i ./n1027.full.fa -i ./n1028.full.fa
 -i ./n1029.full.fa -i ./n1030.full.fa -i ./n1031.full.fa -i ./n1032.full.fa -o ./n1014.reduced.fa -o ./n1015.reduced.fa -o ./n1016.reduced.fa -o ./n1017.reduced.fa -o ./n1018.
reduced.fa -o ./n1019.reduced.fa -o ./n1020.reduced.fa -o ./n1021.reduced.fa -o ./n1022.reduced.fa -o ./n1023.reduced.fa -o ./n1026.reduced.fa -o ./n1027.reduced.fa -o ./n1028.
reduced.fa -o ./n1029.reduced.fa -o ./n1030.reduced.fa -o ./n1031.reduced.fa -o ./n1032.reduced.fa -x ./n1033.full.fa -s ./n1033.count.tsv
...
starting propagation for n1493.full.fa
/home/simone/prophyle/lib/python3.5/site-packages/prophyle/prophyle_assembler/prophyle_assembler -S -k 31 -i ./n1431.full.fa -i ./n1434.full.fa -i ./n1438.full.fa -i ./n1443.fu
ll.fa -i ./n1444.full.fa -i ./n1445.full.fa -i ./n1446.full.fa -i ./n1447.full.fa -i ./n1448.full.fa -i ./n1449.full.fa -i ./n1455.full.fa -i ./n1456.full.fa -i ./n1457.full.fa
 -i ./n1458.full.fa -i ./n1459.full.fa -i ./n1460.full.fa -i ./n1461.full.fa -i ./n1462.full.fa -i ./n1463.full.fa -i ./n1464.full.fa -i ./n1465.full.fa -i ./n1466.full.fa -i .
/n1467.full.fa -i ./n1468.full.fa -i ./n1469.full.fa -i ./n1470.full.fa -i ./n1471.full.fa -i ./n1472.full.fa -i ./n1473.full.fa -i ./n1474.full.fa -i ./n1475.full.fa -i ./n147
6.full.fa -i ./n1477.full.fa -i ./n1478.full.fa -i ./n1479.full.fa -i ./n1480.full.fa -i ./n1481.full.fa -i ./n1482.full.fa -i ./n1483.full.fa -i ./n1484.full.fa -i ./n1485.ful
l.fa -i ./n1486.full.fa -i ./n1487.full.fa -i ./n1488.full.fa -i ./n1489.full.fa -i ./n1490.full.fa -i ./n1491.full.fa -i ./n1492.full.fa -o ./n1431.reduced.fa -o ./n1434.reduc
ed.fa -o ./n1438.reduced.fa -o ./n1443.reduced.fa -o ./n1444.reduced.fa -o ./n1445.reduced.fa -o ./n1446.reduced.fa -o ./n1447.reduced.fa -o ./n1448.reduced.fa -o ./n1449.reduc
ed.fa -o ./n1455.reduced.fa -o ./n1456.reduced.fa -o ./n1457.reduced.fa -o ./n1458.reduced.fa -o ./n1459.reduced.fa -o ./n1460.reduced.fa -o ./n1461.reduced.fa -o ./n1462.reduc
ed.fa -o ./n1463.reduced.fa -o ./n1464.reduced.fa -o ./n1465.reduced.fa -o ./n1466.reduced.fa -o ./n1467.reduced.fa -o ./n1468.reduced.fa -o ./n1469.reduced.fa -o ./n1470.reduc
ed.fa -o ./n1471.reduced.fa -o ./n1472.reduced.fa -o ./n1473.reduced.fa -o ./n1474.reduced.fa -o ./n1475.reduced.fa -o ./n1476.reduced.fa -o ./n1477.reduced.fa -o ./n1478.reduc
ed.fa -o ./n1479.reduced.fa -o ./n1480.reduced.fa -o ./n1481.reduced.fa -o ./n1482.reduced.fa -o ./n1483.reduced.fa -o ./n1484.reduced.fa -o ./n1485.reduced.fa -o ./n1486.reduc
ed.fa -o ./n1487.reduced.fa -o ./n1488.reduced.fa -o ./n1489.reduced.fa -o ./n1490.reduced.fa -o ./n1491.reduced.fa -o ./n1492.reduced.fa -x ./n1493.full.fa -s ./n1493.count.ts
v
...
starting propagation for n1667.full.fa
/home/simone/prophyle/lib/python3.5/site-packages/prophyle/prophyle_assembler/prophyle_assembler -S -k 31 -i ./n1661.full.fa -i ./n1666.full.fa -o ./n1661.reduced.fa -o ./n1666
.reduced.fa -x ./n1667.full.fa -s ./n1667.count.tsv
Makefile:7417: recipe for target 'n1033.full.fa' failed
make: *** [n1033.full.fa] Killed
make: *** Waiting for unfinished jobs....
Makefile:10890: recipe for target 'n1493.full.fa' failed
make: *** [n1493.full.fa] Killed
make: Leaving directory '/home/simone/prophyle/bacteria_idx/propagation'
[prophyle] 2017-04-20 19:39:59 Unfinished, an error occurred (error code 2): make -j 8 -C bacteria_idx/propagation V=1 PRG_ASM=/home/simone/prophyle/lib/python3.5/site-packages
/prophyle/prophyle_assembler/prophyle_assembler
Traceback (most recent call last):
  File "/home/simone/prophyle/bin/prophyle", line 11, in <module>
    load_entry_point('prophyle==0.1.0.29', 'console_scripts', 'prophyle')()
  File "/home/simone/prophyle/lib/python3.5/site-packages/prophyle/prophyle.py", line 1070, in main
    no_prefixes=args.no_prefixes,
  File "/home/simone/prophyle/lib/python3.5/site-packages/prophyle/prophyle.py", line 680, in prophyle_index
    _propagate(index_dir, threads=threads)
  File "/home/simone/prophyle/lib/python3.5/site-packages/prophyle/prophyle.py", line 496, in _propagate
    _run_safe(command)
  File "/home/simone/prophyle/lib/python3.5/site-packages/prophyle/prophyle.py", line 200, in _run_safe
    raise RuntimeError("Command error.")
RuntimeError: Command error.
```

**Comment by karel-brinda** [comment]
@simonepignotti Simone, do you have the last version of ProPhyle? It should already your print memory consumption, but here I cannot see it in your outputs. On my Macbook propagation worked fine (with 4 cores). I am not sure about the reason but I think that it might be due to a different implementation of the C++ STL library (it is sometimes a little bit unpredictable). I use STL `unordered_set`s and they use a lot of memory. We should find some better solution. Khash (by @lh3) might work better.

We might also implement some mechanism to detect lack of memory during propagation. When assembler exits with this error, we could restart the task with less cores.

**Comment by simonepignotti** [comment]
Nope sorry, I was using version 0.1.0.29. I will run it again with the last version from git!

**Comment by simonepignotti** [comment]
Same result using 0.1.0.32:
```
...
Makefile:7417: recipe for target '1883.full.fa' failed
make: *** [1883.full.fa] Killed
make: *** Waiting for unfinished jobs....
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Makefile:10890: recipe for target '562.full.fa' failed
make: *** [562.full.fa] Aborted
make: Leaving directory '/home/simone/git/prophyle/prophyle_latest/idx_bacteria/propagation'
[prophyle] 2017-04-21 00:33:15 Unfinished, an error occurred (error code 2, 0.8 MB used): make -j 8 -C idx_bacteria/propagation V=1 PRG_ASM=/usr/local/lib/python3.5/dist-packages/prophyle/prophyle_assembler/prophyle_assembler
Traceback (most recent call last):
  File "/usr/local/bin/prophyle", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/prophyle/prophyle.py", line 1098, in main
    no_prefixes=args.no_prefixes,
  File "/usr/local/lib/python3.5/dist-packages/prophyle/prophyle.py", line 699, in prophyle_index
    _propagate(index_dir, threads=threads)
  File "/usr/local/lib/python3.5/dist-packages/prophyle/prophyle.py", line 514, in _propagate
    _run_safe(command)
  File "/usr/local/lib/python3.5/dist-packages/prophyle/prophyle.py", line 215, in _run_safe
    raise RuntimeError("Command error.")
RuntimeError: Command error.
```
Log file:
```
...
[prophyle] 2017-04-21 00:04:24 Running k-mer propagation
[prophyle] 2017-04-21 00:04:24 Running: make -j 8 -C idx_bacteria/propagation V=1 PRG_ASM=/usr/local/lib/python3.5/dist-packages/prophyle/prophyle_assembler/prophyle_assembler
[prophyle] 2017-04-21 00:33:15 Unfinished, an error occurred (error code 2, 0.8 MB used): make -j 8 -C idx_bacteria/propagation V=1 PRG_ASM=/usr/local/lib/python3.5/dist-packages/prophyle/prophyle_assembler/prophyle_assembler
```

**Comment by karel-brinda** [comment]
@simonepignotti  Simone, could you provide a full output, please (without ...)? I would like to see what were the assembler lines before dying.

**Comment by simonepignotti** [comment]
@karel-brinda I launched it again on 4 threads and saved the output (I just omitted the concatenation, it was too big for pastebin). This time it failed on a different node.
[stdout](https://pastebin.com/zgkW9if0)
[stderr](https://pastebin.com/XZHq9j0n)
[log](https://pastebin.com/RdpKVckr)

**Comment by karel-brinda** [comment]
Ok, I cannot see much from it as I am using the silence parameter `-S` :). Nevertheless, I think I understand well what's happening inside.

**Comment by karel-brinda** [comment]
I will add those two features discussed today over Skype. However, it might be complicated to test them. Simone, could you keep your index in order to be able to reproduce the problem again? First, I will modify the `new_handler` and wait several seconds. Second, I will implement the memory-efficient mode and I will use it automatically for nodes with too many children.

**Comment by karel-brinda** [comment]
@simonepignotti  Btw. Simone, it is interesting that it happens on that computer. I don't remember that I would ever observe it there. Please, could you run it once again with `time` and copy the memory results here? I would like to know how much memory it took according to this program...

**Comment by karel-brinda** [comment]
Simone, when you use two cores, does index construction finish (including klcp & sa)?

**Comment by simonepignotti** [comment]
Yes Karel, it does finish when launched on two threads.
