### ISSUE TITLE
psutil.AccessDenied

### ISSUE THREAD

**Issue by karel-brinda** [karel-brinda/prophyle#225]
```
$ ./test3_analyze.sh 
[prophyle] 2017-07-03 13:01:56 Running: /Users/karel/github/my/prophyle/prophyle/prophyle_analyze.py ./_index_test _test_analyze.basic - -t otu -l -1
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/psutil/_psosx.py", line 196, in wrapper
    return fun(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/psutil/_psosx.py", line 266, in memory_info
    rss, vms = cext.proc_memory_info(self.pid)[:2]
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./prophyle/prophyle.py", line 1290, in <module>
    main()
  File "./prophyle/prophyle.py", line 1266, in main
    max_lines=args.max_lines
  File "./prophyle/prophyle.py", line 819, in prophyle_analyze
    pro.run_safe(cmd_analyze)
  File "/Users/karel/github/my/prophyle/prophyle/prophylelib.py", line 424, in run_safe
    max_rss = max(max_rss, ps_p.memory_info().rss)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/psutil/__init__.py", line 935, in memory_info
    return self._proc.memory_info()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/psutil/_psosx.py", line 208, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=59835)
```

**Comment by karel-brinda** [comment]
Fixed by https://github.com/karel-brinda/prophyle/commit/38a75d9a08ab621793b8b4d0cedbfd908c39aace
