### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by karel-brinda** [karel-brinda/prophyle#228]
```
./test_index.sh 
+ ./prophyle/prophyle.py download bacteria
[prophyle] 2017-07-06 22:51:24 Downloading "bacteria" started
[prophyle] 2017-07-06 22:51:24 Checking library 'bacteria' in '/Users/karel/prophyle/bacteria'
[prophyle] 2017-07-06 22:51:24 Skipping downloading library '/Users/karel/prophyle' (already exists)
[prophyle] 2017-07-06 22:51:24 Downloading "bacteria" finished
+ ./prophyle/prophyle.py index -k 5 -s 0.05 -T /Users/karel/prophyle/bacteria.nw _index_test
[prophyle] 2017-07-06 22:51:25 Index construction started
[prophyle] 2017-07-06 22:51:25 Running: make -C /Users/karel/github/my/prophyle/prophyle
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C prophyle_assembler
make[1]: Nothing to be done for `all'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C prophyle_index
make[1]: Nothing to be done for `all'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C prophyle_assignment
make[1]: Nothing to be done for `all'.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/psutil/_psosx.py", line 196, in wrapper
    return fun(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/psutil/_psosx.py", line 266, in memory_info
    rss, vms = cext.proc_memory_info(self.pid)[:2]
PermissionError: [Errno 13] Permission denied
```

**Comment by karel-brinda** [comment]
fixed by https://github.com/karel-brinda/prophyle/commit/90f662743653794786b220aae632dd155284b3ef
