### ISSUE TITLE
six dependency (from ete3)

### ISSUE THREAD

**Issue by simonepignotti** [karel-brinda/prophyle#240]
`ete3`'s dependency `six` is not automatically installed when using `pip`.

**Comment by karel-brinda** [comment]
Could you copy the error log, please? Which version of ete3 do you use?

On Mon, Jul 24, 2017 at 6:02 AM Simone Pignotti <notifications@github.com>
wrote:

> ete3's dependency six is not automatically installed when using pip.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_karel-2Dbrinda_prophyle_issues_240&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Vsp5SEA7fPwK_yJy_kNBcccLfFrWCVrk92HHgartOZs&m=tHF3BcaBox2P0v305x-WySwYnA51irXs81AVqSdxGHE&s=UR5qx1PmfAveKU0AdZGTWoG4U_wqns1VjhKvIyAiUHY&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AIX1Jo9xQPmvIwnF8f6CZbNKqbKPco3yks5sRGuigaJpZM4Og-2DUW&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Vsp5SEA7fPwK_yJy_kNBcccLfFrWCVrk92HHgartOZs&m=tHF3BcaBox2P0v305x-WySwYnA51irXs81AVqSdxGHE&s=07cOkNvPLjDQVqbpR3-2eL84-R3_IvcXgm_o3BxnsKk&e=>
> .
>
-- 
Sent from my iPad

**Comment by simonepignotti** [comment]
I used the `--no-cache-dir` option, so the last version was correctly retrieved but its dependency was not installed:
```
(minimal) [simone@archsimo ~]$ pip install --no-cache-dir prophyle
Collecting prophyle
  Downloading prophyle-0.2.0.3-py3-none-any.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 8.4MB/s 
Requirement already satisfied: wheel in ./.miniconda/envs/minimal/lib/python3.6/site-packages (from prophyle)
Collecting ete3 (from prophyle)
  Downloading ete3-3.0.0b35.tar.gz (10.6MB)
    100% |████████████████████████████████| 10.6MB 13.2MB/s 
Collecting pysam (from prophyle)
  Downloading pysam-0.11.2.2-cp36-cp36m-manylinux1_x86_64.whl (8.4MB)
    100% |████████████████████████████████| 8.4MB 10.5MB/s 
Collecting scipy (from prophyle)
  Downloading scipy-0.19.1-cp36-cp36m-manylinux1_x86_64.whl (48.2MB)
    100% |████████████████████████████████| 48.2MB 12.3MB/s 
Collecting psutil (from prophyle)
  Downloading psutil-5.2.2.tar.gz (348kB)
    100% |████████████████████████████████| 358kB 27.5MB/s 
Collecting bitarray (from prophyle)
  Downloading bitarray-0.8.1.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 26.0MB/s 
Collecting numpy>=1.8.2 (from scipy->prophyle)
  Downloading numpy-1.13.1-cp36-cp36m-manylinux1_x86_64.whl (17.0MB)
    100% |████████████████████████████████| 17.0MB 6.9MB/s 
Installing collected packages: ete3, pysam, numpy, scipy, psutil, bitarray, prophyle
  Running setup.py install for ete3 ... done
  Running setup.py install for psutil ... done
  Running setup.py install for bitarray ... done
Successfully installed bitarray-0.8.1 ete3-3.0.0b35 numpy-1.13.1 prophyle-0.2.0.3 psutil-5.2.2 pysam-0.11.2.2 scipy-0.19.1
(minimal) [simone@archsimo ~]$ which prophyle
/home/simone/.miniconda/envs/minimal/bin/prophyle
(minimal) [simone@archsimo ~]$ prophyle
Traceback (most recent call last):
  File "/home/simone/.miniconda/envs/minimal/bin/prophyle", line 7, in <module>
    from prophyle.prophyle import main
  File "/home/simone/.miniconda/envs/minimal/lib/python3.6/site-packages/prophyle/prophyle.py", line 40, in <module>
    import prophylelib as pro
  File "/home/simone/.miniconda/envs/minimal/lib/python3.6/site-packages/prophyle/prophylelib.py", line 11, in <module>
    import ete3
  File "/home/simone/.miniconda/envs/minimal/lib/python3.6/site-packages/ete3/__init__.py", line 51, in <module>
    from .ncbi_taxonomy import *
  File "/home/simone/.miniconda/envs/minimal/lib/python3.6/site-packages/ete3/ncbi_taxonomy/__init__.py", line 40, in <module>
    from .ncbiquery import *
  File "/home/simone/.miniconda/envs/minimal/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 59, in <module>
    import six
ModuleNotFoundError: No module named 'six'
(minimal) [simone@archsimo ~]$ pip install six
Collecting six
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six
Successfully installed six-1.10.0
(minimal) [simone@archsimo ~]$ prophyle

Program: prophyle (phylogeny-based metagenomic classification)
Version: 0.2.0.3
Authors: Karel Brinda <kbrinda@hsph.harvard.edu>, Kamil Salikhov <kamil.salikhov@univ-mlv.fr>,
		 Simone Pignotti <pignottisimone@gmail.com>, Gregory Kucherov <gregory.kucherov@univ-mlv.fr>

Usage:   prophyle <command> [options]

Command:
  
    download     download a genomic database
    index        build index
    classify     classify reads
    analyze      analyze results

    compress     compress a ProPhyle index (experimental)
    decompress   decompress a compressed ProPhyle index (experimental)
```

**Comment by karel-brinda** [comment]
Fixed by https://github.com/karel-brinda/prophyle/commit/673c1950ecded3cf9676fea56df06787024004ae
