### ISSUE TITLE
Non-working unix pipes - file "/dev/fd/63" does not exist

### ISSUE THREAD

**Issue by karel-brinda** [karel-brinda/prophyle#260]
```
$ prophyle classify -P "sparc1_k18" <(head -n 100 sparc_minion_02.fq)
[prophyle] 2017-09-20 14:31:35 Classification started
[prophyle] 2017-09-20 14:31:35 Running: make -C /home/kb219/miniconda/envs/p/lib/python3.6/site-packages/prophyle
make: Entering directory `/home/kb219/miniconda/envs/p/lib/python3.6/site-packages/prophyle'
make -C prophyle_assembler
make[1]: Entering directory `/home/kb219/miniconda/envs/p/lib/python3.6/site-packages/prophyle/prophyle_assembler'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/kb219/miniconda/envs/p/lib/python3.6/site-packages/prophyle/prophyle_assembler'
make -C prophyle_index
make[1]: Entering directory `/home/kb219/miniconda/envs/p/lib/python3.6/site-packages/prophyle/prophyle_index'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/kb219/miniconda/envs/p/lib/python3.6/site-packages/prophyle/prophyle_index'
make -C prophyle_assignment
make[1]: Entering directory `/home/kb219/miniconda/envs/p/lib/python3.6/site-packages/prophyle/prophyle_assignment'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/kb219/miniconda/envs/p/lib/python3.6/site-packages/prophyle/prophyle_assignment'
make: Leaving directory `/home/kb219/miniconda/envs/p/lib/python3.6/site-packages/prophyle'
[prophyle] 2017-09-20 14:31:35 Finished (0.0 MB used): make -C /home/kb219/miniconda/envs/p/lib/python3.6/site-packages/prophyle
[prophyle] 2017-09-20 14:31:35 Automatic detection of k-mer length: k=18
Traceback (most recent call last):
  File "/home/kb219/miniconda/envs/p/bin/prophyle", line 11, in <module>
    sys.exit(main())
  File "/home/kb219/miniconda/envs/p/lib/python3.6/site-packages/prophyle/prophyle.py", line 1439, in main
    cimpl=args.cimpl,
  File "/home/kb219/miniconda/envs/p/lib/python3.6/site-packages/prophyle/prophyle.py", line 806, in prophyle_classify
    pro.test_files(fq_fn)
  File "/home/kb219/miniconda/envs/p/lib/python3.6/site-packages/prophyle/prophylelib.py", line 381, in test_files
    assert os.path.isfile(fn), 'File "{}" does not exist.'.format(fn)
AssertionError: File "/dev/fd/63" does not exist.

```

**Comment by karel-brinda** [comment]
We should assess which files can be provided through unix pipes. For these files we should add a pipe option to the testing function. We should also verify if we are currently testing those input files that support passing '-' as file name.

**Comment by karel-brinda** [comment]
The current issue is that we don't (and maybe can't) pass process substitution from `prophyle` to `prophyle_index`

```
../../prophyle/prophyle.py classify index <(head -n 1 reads.fq) | samtools view -h - > class_pipe.sam
[prophyle] 2017-11-11 13:11:21 Classification started
[prophyle] 2017-11-11 13:11:21 Shell command: make -j -s -C /Users/karel/github/my/prophyle/prophyle
[prophyle] 2017-11-11 13:11:22 Finished (0.4 MB used): make -j -s -C /Users/karel/github/my/prophyle/prophyle
[prophyle] 2017-11-11 13:11:22 Automatic detection of k-mer length: k=3
[prophyle] 2017-11-11 13:11:22 k-LCP file found, going to use rolling window
[prophyle] 2017-11-11 13:11:22 Shell command: /Users/karel/github/my/prophyle/prophyle/prophyle_index/prophyle_index query -k 3 -u  index/index.fa /dev/fd/63 | /Users/karel/github/my/prophyle/prophyle/prophyle_assignment.py -m h1 -f sam index/tree.nw 3 -
klcp_loading	0.00s
[bwa_seq_open] fail to open file '/dev/fd/63' : Bad file descriptor
[prophyle] 2017-11-11 13:11:22 Unfinished, an error occurred (error code 1, 1.1 MB used): /Users/karel/github/my/prophyle/prophyle/prophyle_index/prophyle_index query -k 3 -u  index/index.fa /dev/fd/63 | /Users/karel/github/my/prophyle/prophyle/prophyle_assignment.py -m h1 -f sam index/tree.nw 3 -
Traceback (most recent call last):
  File "../../prophyle/prophyle.py", line 1612, in <module>
    main()
  File "../../prophyle/prophyle.py", line 1543, in main
    prophyle_conf_string=prophyle_conf_string, # already preprocessed
  File "../../prophyle/prophyle.py", line 913, in prophyle_classify
    pro.run_safe(command)
  File "/Users/karel/github/my/prophyle/prophyle/prophylelib.py", line 487, in run_safe
    raise RuntimeError("A command failed, see messages above.")
RuntimeError: A command failed, see messages above.
make: *** [dp] Error 1
```
