### ISSUE TITLE
print_sam_line missing required positional argument 'suffix'

### ISSUE THREAD

**Issue by simonepignotti** [karel-brinda/prophyle#262]
Missing parameter using python assignment implementation. C version works fine on the same data. It could be machine-dependent, since I don't have this problem on my laptop. 

```
Traceback (most recent call last):
  File "/home/pignotti/data/git_prophyle/prophyle/prophyle_assignment.py", line 665, in <module>
    main()
  File "/home/pignotti/data/git_prophyle/prophyle/prophyle_assignment.py", line 644, in main
    dont_translate_blocks=d,
  File "/home/pignotti/data/git_prophyle/prophyle/prophyle_assignment.py", line 555, in assign
    read.process_krakline(x, form=form, crit=crit)
  File "/home/pignotti/data/git_prophyle/prophyle/prophyle_assignment.py", line 86, in process_krakline
    self.print_assignments(form, crit)
  File "/home/pignotti/data/git_prophyle/prophyle/prophyle_assignment.py", line 211, in print_assignments
    self.print_sam_line(None)
TypeError: print_sam_line() missing 1 required positional argument: 'suffix'
[prophyle] 2017-09-25 12:59:29 Unfinished, an error occurred (error code 1, 2.7 MB used): /home/pignotti/data/git_prophyle/prophyle/prophyle_index/prophyle_in
dex query -k 31 -u  /mnt/disk/pignotti/exp_hmp_mock/idx/index.fa reads/SRR172903.fastq | /home/pignotti/data/git_prophyle/prophyle/prophyle_assignment.py -m h
1 -f sam /mnt/disk/pignotti/exp_hmp_mock/idx/tree.nw 31 -
Traceback (most recent call last):
  File "/home/pignotti/data/git_prophyle/prophyle/prophyle.py", line 1505, in <module>
    main()
  File "/home/pignotti/data/git_prophyle/prophyle/prophyle.py", line 1439, in main
    cimpl=args.cimpl,
  File "/home/pignotti/data/git_prophyle/prophyle/prophyle.py", line 856, in prophyle_classify
    pro.run_safe(command)
  File "/mnt/disk/pignotti/git_prophyle/prophyle/prophylelib.py", line 460, in run_safe
    raise RuntimeError("A command failed, see messages above.")
RuntimeError: A command failed, see messages above.
```

**Comment by karel-brinda** [comment]
Simone, which version is it? Try to use the last version from the devel branch. It should be already fixed there.

**Comment by simonepignotti** [comment]
Ok, I was using master. I will try immediately!

**Comment by simonepignotti** [comment]
I confirm it's solved, thanks Karel!
