### ISSUE TITLE
Exception not caught with coverage and LCA in branch devel

### ISSUE THREAD

**Issue by simonepignotti** [karel-brinda/prophyle#265]
I ran classify with both options for coverage and tie-lca by mistake, and the program exits without any explanation. We should not accept the two options together and return a clear error message.
```
[prophyle] 2017-09-27 09:12:13 Running: /mnt/disk/pignotti/git_prophyle/prophyle/prophyle_index/prophyle_index query -k 31 -u  ../kraken_lib/krapro_dustmask_idx/index.fa reads/simulated.fastq | /mnt/disk/pignotti/git_prophyle/prophyle/prophyle_assignment.py -m c1 -f sam ../kraken_lib/krapro_dustmask_idx/tree.nw 31 - -L
klcp_loading    6.05s
Traceback (most recent call last):
  File "/mnt/disk/pignotti/git_prophyle/prophyle/prophyle_assignment.py", line 666, in <module>
    main()
  File "/mnt/disk/pignotti/git_prophyle/prophyle/prophyle_assignment.py", line 645, in main
    dont_translate_blocks=d,
  File "/mnt/disk/pignotti/git_prophyle/prophyle/prophyle_assignment.py", line 556, in assign
    read.process_krakline(x, form=form, crit=crit)
  File "/mnt/disk/pignotti/git_prophyle/prophyle/prophyle_assignment.py", line 86, in process_krakline
    self.print_assignments(form, crit)
  File "/mnt/disk/pignotti/git_prophyle/prophyle/prophyle_assignment.py", line 262, in print_assignments
    asg['covcigar'] = cigar_from_mask(asg['covmask'])
KeyError: 'covmask'
[prophyle] 2017-09-27 09:13:49 Unfinished, an error occurred (error code 1, 2.8 MB used): /mnt/disk/pignotti/git_prophyle/prophyle/prophyle_index/prophyle_index query -k 31 -u  ../kraken_lib/krapro_dustmask_idx/index.fa reads/simulated.fastq | /mnt/disk/pignotti/git_prophyle/prophyle/prophyle_assignment.py -m c1 -f sam ../kraken_lib/krapro_dustmask_idx/tree.nw 31 - -L
Traceback (most recent call last):
  File "/mnt/disk/pignotti/git_prophyle/prophyle/prophyle.py", line 1535, in <module>
    main()
  File "/mnt/disk/pignotti/git_prophyle/prophyle/prophyle.py", line 1467, in main
    force_restarted_search=args.force_restarted_search,
  File "/mnt/disk/pignotti/git_prophyle/prophyle/prophyle.py", line 872, in prophyle_classify
    pro.run_safe(command)
  File "/mnt/disk/pignotti/git_prophyle/prophyle/prophylelib.py", line 463, in run_safe
    raise RuntimeError("A command failed, see messages above.")
RuntimeError: A command failed, see messages above.
```

**Comment by karel-brinda** [comment]
Could you copy the command here?

On Wed, Sep 27, 2017 at 4:12 AM Simone Pignotti <notifications@github.com>
wrote:

> I ran classify with both options for coverage and tie-lca by mistake, and
> the program exits without any explanation. We should not accept the two
> options together and return a clear error message.
>
> [prophyle] 2017-09-27 09:12:13 Running: /mnt/disk/pignotti/git_prophyle/prophyle/prophyle_index/prophyle_index query -k 31 -u  ../kraken_lib/krapro_dustmask_idx/index.fa reads/simulated.fastq | /mnt/disk/pignotti/git_prophyle/prophyle/prophyle_assignment.py -m c1 -f sam ../kraken_lib/krapro_dustmask_idx/tree.nw 31 - -L
> klcp_loading    6.05s
> Traceback (most recent call last):
>   File "/mnt/disk/pignotti/git_prophyle/prophyle/prophyle_assignment.py", line 666, in <module>
>     main()
>   File "/mnt/disk/pignotti/git_prophyle/prophyle/prophyle_assignment.py", line 645, in main
>     dont_translate_blocks=d,
>   File "/mnt/disk/pignotti/git_prophyle/prophyle/prophyle_assignment.py", line 556, in assign
>     read.process_krakline(x, form=form, crit=crit)
>   File "/mnt/disk/pignotti/git_prophyle/prophyle/prophyle_assignment.py", line 86, in process_krakline
>     self.print_assignments(form, crit)
>   File "/mnt/disk/pignotti/git_prophyle/prophyle/prophyle_assignment.py", line 262, in print_assignments
>     asg['covcigar'] = cigar_from_mask(asg['covmask'])
> KeyError: 'covmask'
> [prophyle] 2017-09-27 09:13:49 Unfinished, an error occurred (error code 1, 2.8 MB used): /mnt/disk/pignotti/git_prophyle/prophyle/prophyle_index/prophyle_index query -k 31 -u  ../kraken_lib/krapro_dustmask_idx/index.fa reads/simulated.fastq | /mnt/disk/pignotti/git_prophyle/prophyle/prophyle_assignment.py -m c1 -f sam ../kraken_lib/krapro_dustmask_idx/tree.nw 31 - -L
> Traceback (most recent call last):
>   File "/mnt/disk/pignotti/git_prophyle/prophyle/prophyle.py", line 1535, in <module>
>     main()
>   File "/mnt/disk/pignotti/git_prophyle/prophyle/prophyle.py", line 1467, in main
>     force_restarted_search=args.force_restarted_search,
>   File "/mnt/disk/pignotti/git_prophyle/prophyle/prophyle.py", line 872, in prophyle_classify
>     pro.run_safe(command)
>   File "/mnt/disk/pignotti/git_prophyle/prophyle/prophylelib.py", line 463, in run_safe
>     raise RuntimeError("A command failed, see messages above.")
> RuntimeError: A command failed, see messages above.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_karel-2Dbrinda_prophyle_issues_265&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Vsp5SEA7fPwK_yJy_kNBcccLfFrWCVrk92HHgartOZs&m=z1LLK5U5LqTtX1Q_hjGMjp0faeEQYFXRhPRU94JnaH4&s=mh37cuWAYMKZPz_zkNRbxTdRa5L_WG6X3xNOhfNEgJE&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AIX1JhJqAIGoF3V8e1ic3Z76n-2DIBLGrAks5smgN4gaJpZM4PlYQB&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Vsp5SEA7fPwK_yJy_kNBcccLfFrWCVrk92HHgartOZs&m=z1LLK5U5LqTtX1Q_hjGMjp0faeEQYFXRhPRU94JnaH4&s=uFjEryI2qtp1fU-FhTGxGs6jNmCpl8nn_zaAzC5AjS4&e=>
> .
>
-- 
Sent from my iPad

**Comment by simonepignotti** [comment]
It's actually a problem of tie-lca in general, even running:
`../git_prophyle/prophyle/prophyle.py classify -L ../kraken_lib/krapro_idx/ prova.fastq > prova_lca.sam`
gives the same error.

**Comment by karel-brinda** [comment]
Thank you for reporting. The LCA mode is quite tricky because multiple different values (e.g., c2) can exist for a single tag before doing the LCA. I will have to carefully debug this part.
