### ISSUE TITLE
Viruses/all.fna.tar.gz does not exist

### ISSUE THREAD

**Issue by karel-brinda** [karel-brinda/prophyle#284]
```
[kb219@compute-a-16-71 ~]$ prophyle download viruses
[prophyle] 2017-11-13 23:31:08 Downloading "viruses" started
[prophyle] 2017-11-13 23:31:08 Checking library 'viruses' in '/home/kb219/prophyle/viruses'
[prophyle] 2017-11-13 23:31:08 Downloading library '/home/kb219/prophyle'
[prophyle] 2017-11-13 23:31:08 Copying Newick/NHX tree '/n/scratch2/kb219/miniconda/lib/python3.6/site-packages/prophyle/trees/viruses.nw' to '/home/kb219/prophyle/viruses/../viruses.nw'
[prophyle] 2017-11-13 23:31:08 Shell command: cd /home/kb219/prophyle/viruses && curl https://ftp.ncbi.nlm.nih.gov/genomes/Viruses/all.fna.tar.gz | tar xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   992    0   992    0     0   4001      0 --:--:-- --:--:-- --:--:--  4016

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
[prophyle] 2017-11-13 23:31:08 Unfinished, an error occurred (error code 2, 1.5 MB used): cd /home/kb219/prophyle/viruses && curl https://ftp.ncbi.nlm.nih.gov/genomes/Viruses/all.fna.tar.gz | tar xz
Traceback (most recent call last):
  File "/home/kb219/miniconda/bin/prophyle", line 6, in <module>
    sys.exit(prophyle.prophyle.main())
  File "/home/kb219/miniconda/lib/python3.6/site-packages/prophyle/prophyle.py", line 1490, in main
    force=args.force,
  File "/home/kb219/miniconda/lib/python3.6/site-packages/prophyle/prophyle.py", line 337, in prophyle_download
    pro.run_safe(cmd)
  File "/home/kb219/miniconda/lib/python3.6/site-packages/prophyle/prophylelib.py", line 487, in run_safe
    raise RuntimeError("A command failed, see messages above.")
RuntimeError: A command failed, see messages above.
```

**Comment by karel-brinda** [comment]
Fixed by https://github.com/karel-brinda/prophyle/commit/3fcbfbb67b1e53da3abfdb9f8bdf127e39c8edcc
